<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name=generator content="HydePHP">

    <title>HydePHP</title>

    <!-- The main stylesheet generated by the app -->
    <link rel="stylesheet" href="{{ relative_path('media/app.css', $currentPage) }}">

    @include('layouts.meta') 
</head>
<body id="app">
    @include('layouts.navigation') 

    <section id="content">
        @yield('content') 
    </section>

    @include('layouts.footer') 
</body>
</html>
